{
 "openapi": "3.0.0",
 "info": {
  "title": "Limestone Networks API",
  "description": "LSN API Documentation",
  "contact": {
   "email": "support@limestonenetworks.com"
  },
  "version": "v2.0.0"
 },
 "servers": [
  {
   "url": "https://api.dallas-idc.com",
   "description": "Limestone Network API Host",
   "x-public": true
  }
 ],
 "paths": {
  "/v2/server/{server}/tags": {
   "get": {
    "tags": [
     "Server"
    ],
    "summary": "Get server tags",
    "operationId": "0dcb8569924482ab184b96de37b8c38b",
    "x-public": true,
    "x-version": "v2"
   },
   "post": {
    "tags": [
     "Server"
    ],
    "summary": "Create a new server tag",
    "operationId": "4ce7ac988cf6fe12c63778a63458555b",
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/server/{server}/tags/{tag_name}": {
   "delete": {
    "tags": [
     "Server"
    ],
    "summary": "Remove a server tag",
    "operationId": "c0b3b41316eb12a9be86a0ce26b7b70a",
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/client/{client_id}/metadata": {
   "post": {
    "tags": [
     "Client"
    ],
    "summary": "Create metadata",
    "description": "Create metadata for the client",
    "operationId": "createMetadata",
    "security": [
     {
      "bearerAuth": [
       "clients"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/core": {
   "get": {
    "tags": [
     "Core"
    ],
    "summary": "Get all core",
    "description": "Get all cores",
    "operationId": "getCoreList",
    "security": [
     {
      "bearerAuth": [
       "cores"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/core/{core_name}": {
   "get": {
    "tags": [
     "Core"
    ],
    "summary": "Get a core",
    "description": "Get a core by name",
    "operationId": "getCore",
    "security": [
     {
      "bearerAuth": [
       "cores"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/event": {
   "get": {
    "tags": [
     "EventLog"
    ],
    "summary": "Get event logs",
    "description": "Get and filter event log list",
    "operationId": "getEventList",
    "security": [
     {
      "bearerAuth": [
       "events"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/event/{event_id}": {
   "get": {
    "tags": [
     "EventLog"
    ],
    "summary": "Get event log",
    "description": "Get event log by id",
    "operationId": "getEvent",
    "security": [
     {
      "bearerAuth": [
       "events"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/facility": {
   "get": {
    "tags": [
     "Facility"
    ],
    "summary": "Get all facilities",
    "description": "Get all facilities",
    "operationId": "getFacilityList",
    "security": [
     {
      "bearerAuth": [
       "facilities"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/facility/{facility_name}": {
   "get": {
    "tags": [
     "Facility"
    ],
    "summary": "Get a facility",
    "description": "Get a facility by name",
    "operationId": "getFacility",
    "security": [
     {
      "bearerAuth": [
       "facilities"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/facility/{facility_name}/stock": {
   "get": {
    "tags": [
     "Facility"
    ],
    "summary": "Get a facility's stock",
    "description": "Get a facility's stock by name",
    "operationId": "getFacilityStock",
    "security": [
     {
      "bearerAuth": [
       "facilities"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/image": {
   "get": {
    "tags": [
     "Image"
    ],
    "summary": "Get all images",
    "description": "Get all images",
    "operationId": "getImageList",
    "security": [
     {
      "bearerAuth": [
       "images"
      ]
     }
    ],
    "x-public": true
   }
  },
  "/v2/image/{image_name}": {
   "get": {
    "tags": [
     "Image"
    ],
    "summary": "Get an image",
    "description": "Get an image by name",
    "operationId": "getImage",
    "security": [
     {
      "bearerAuth": [
       "images"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/instance": {
   "get": {
    "tags": [
     "Instance"
    ],
    "summary": "Get all instances",
    "description": "Get all instances",
    "operationId": "getInstanceList",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "post": {
    "tags": [
     "Instance"
    ],
    "summary": "Create an instance",
    "description": "Create a server based on the given options",
    "operationId": "storeInstance",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/instance/{instance_id}": {
   "get": {
    "tags": [
     "Instance"
    ],
    "summary": "Get an instance",
    "description": "Get an instance by ID",
    "operationId": "getInstance",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "put": {
    "tags": [
     "Instance"
    ],
    "summary": "Reload an instance",
    "description": "Reload a server based on the given options",
    "operationId": "reloadInstance",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "delete": {
    "tags": [
     "Instance"
    ],
    "summary": "Delete an instance",
    "description": "Delete an instance. This will cancel the instance",
    "operationId": "deleteInstance",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/instance/{instance_id}/subnet": {
   "get": {
    "tags": [
     "Instance"
    ],
    "summary": "Get an instance's IP subnets",
    "description": "Get an instance's IP subnets",
    "operationId": "getInstanceIPSubnets",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "post": {
    "tags": [
     "Instance"
    ],
    "summary": "Assign an IP subnet to an instance",
    "description": "Assign an IP subnet to an instance",
    "operationId": "assignIPSubnet",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "delete": {
    "tags": [
     "Instance"
    ],
    "summary": "Remove an IP subnet from an instance",
    "description": "Remove an IP subnet from an instance",
    "operationId": "deassignIPSubnet",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/instance/{instance_id}/metadata": {
   "get": {
    "tags": [
     "Instance"
    ],
    "summary": "Get all metadata",
    "description": "Get all metadata for an instance",
    "operationId": "getMetadata",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "post": {
    "tags": [
     "Instance"
    ],
    "summary": "Create metadata",
    "description": "Create metadata for the instance",
    "operationId": "createMetadata",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/instance/{instance_id}/metadata/{key}": {
   "put": {
    "tags": [
     "Instance"
    ],
    "summary": "Update metadata",
    "description": "Update metadata for the instance",
    "operationId": "updateMetadata",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "delete": {
    "tags": [
     "Instance"
    ],
    "summary": "Delete metadata",
    "description": "Delete metadata from an instance",
    "operationId": "deleteMetadata",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/instance/{instance_id}/tag": {
   "get": {
    "tags": [
     "Instance"
    ],
    "summary": "Get all tags",
    "description": "Get all tags for an instance",
    "operationId": "getTags",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "post": {
    "tags": [
     "Instance"
    ],
    "summary": "Create tag",
    "description": "Create tag for the instance",
    "operationId": "createTag",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/instance/{instance_id}/tag/{tag}": {
   "delete": {
    "tags": [
     "Instance"
    ],
    "summary": "Delete tag",
    "description": "Delete tag from an instance",
    "operationId": "deleteTag",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/instance/find_by_create_job/{job_id}": {
   "get": {
    "tags": [
     "Instance"
    ],
    "summary": "Get an instance by create Job",
    "description": "Get an instance by create job ID",
    "operationId": "getInstanceByCreateJob",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/instance/{instance_id}/start": {
   "put": {
    "tags": [
     "Instance"
    ],
    "summary": "Start Instance",
    "description": "Send power on command to instance",
    "operationId": "startInstance",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/instance/{instance_id}/stop": {
   "put": {
    "tags": [
     "Instance"
    ],
    "summary": "Stop Instance",
    "description": "Send power off command to instance",
    "operationId": "stopInstance",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/instance/{instance_id}/restart": {
   "put": {
    "tags": [
     "Instance"
    ],
    "summary": "Restart Instance",
    "description": "Send power restart command to instance",
    "operationId": "restartInstance",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/instance/{instance_id}/power": {
   "get": {
    "tags": [
     "Instance"
    ],
    "summary": "Get instance power status",
    "description": "Get instance power status",
    "operationId": "instancePowerStatus",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/job/{job_id}": {
   "get": {
    "tags": [
     "Job"
    ],
    "summary": "Get a job",
    "description": "Get a job by ID",
    "operationId": "getJob",
    "security": [
     {
      "bearerAuth": [
       "jobs"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/job/history": {
   "get": {
    "tags": [
     "Job"
    ],
    "summary": "Get job history for object",
    "description": "Get a job history",
    "operationId": "getJobHistory",
    "security": [
     {
      "bearerAuth": [
       "jobs"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/project": {
   "get": {
    "tags": [
     "Project"
    ],
    "summary": "Get all projects",
    "description": "Get all projects",
    "operationId": "getProjectList",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "post": {
    "tags": [
     "Project"
    ],
    "summary": "Create a project",
    "description": "Create a project based on the given options",
    "operationId": "storeProject",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/project/{project_id}": {
   "get": {
    "tags": [
     "Project"
    ],
    "summary": "Get a project",
    "description": "Get a project by ID",
    "operationId": "getProject",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "delete": {
    "tags": [
     "Project"
    ],
    "summary": "Delete a project",
    "description": "Delete a project by ID. All dependent resources must be deleted prior.",
    "operationId": "deleteProject",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/project/{project_id}/status": {
   "put": {
    "tags": [
     "Project"
    ],
    "summary": "Update a project status",
    "description": "Update a project status by ID.",
    "operationId": "updateProjectStatus",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/project/{project_id}/quotas": {
   "get": {
    "tags": [
     "Project"
    ],
    "summary": "Get a project's quotas",
    "description": "Get a project's quotas by ID",
    "operationId": "getProjectQuotas",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/project/{project_id}/server": {
   "get": {
    "tags": [
     "Project"
    ],
    "summary": "Get a project's instances",
    "description": "Get a project's instances",
    "operationId": "getProjectServers",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "post": {
    "tags": [
     "Project"
    ],
    "summary": "Add a server to a project",
    "description": "Create a server based on the given options",
    "operationId": "storeProjectServer",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/project/{project_id}/server/{server_id}": {
   "post": {
    "tags": [
     "Project"
    ],
    "summary": "Associate a server with a project",
    "description": "Associate a server with a project",
    "operationId": "associateProjectServer",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "delete": {
    "tags": [
     "Project"
    ],
    "summary": "Delete a project's server",
    "description": "Delete a project's server by ID. This will cancel the instance",
    "operationId": "deleteProjectServer",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/project/{project_id}/subnet": {
   "get": {
    "tags": [
     "Project"
    ],
    "summary": "Get an project's IP subnets",
    "description": "Get an project's IP subnets",
    "operationId": "getProjectIPSubnets",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "delete": {
    "tags": [
     "Project"
    ],
    "summary": "Release an IP subnet from a project",
    "description": "Release an IP subnet from a project",
    "operationId": "deallocateIPSubnet",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/project/{project_id}/threshold": {
   "get": {
    "tags": [
     "Project"
    ],
    "summary": "Get a project's billing threshold",
    "description": "Get a project's billing threshold",
    "operationId": "getProjectBillingThreshold",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/project/{project_id}/billing": {
   "get": {
    "tags": [
     "Project"
    ],
    "summary": "Get a project's billing history",
    "description": "Get a project's billing history",
    "operationId": "getProjectBilling",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/sshkey": {
   "get": {
    "tags": [
     "SSHKey"
    ],
    "summary": "Get all ssh keys",
    "description": "Get all ssh keys",
    "operationId": "getSSHKeyList",
    "security": [
     {
      "bearerAuth": [
       "ssh-key-management"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "post": {
    "tags": [
     "SSHKey"
    ],
    "summary": "Create an ssh public key",
    "description": "Create an ssh public key based on the given options",
    "operationId": "storeSSHKey",
    "security": [
     {
      "bearerAuth": [
       "ssh-key-management"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/sshkey/{name}": {
   "get": {
    "tags": [
     "SSHKey"
    ],
    "summary": "Get an ssh key",
    "description": "Get an ssh key",
    "operationId": "getSSHKey",
    "security": [
     {
      "bearerAuth": [
       "ssh-key-management"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   },
   "delete": {
    "tags": [
     "SSHKey"
    ],
    "summary": "Delete an ssh key",
    "description": "Delete an ssh key",
    "operationId": "deleteSSHKey",
    "security": [
     {
      "bearerAuth": [
       "ssh-key-management"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/current_user": {
   "get": {
    "tags": [
     "User"
    ],
    "summary": "Get user",
    "description": "Get a user by ID",
    "operationId": "getCurrentUser",
    "security": [
     {
      "bearerAuth": [
       "users"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  },
  "/v2/user/can_create_project": {
   "get": {
    "tags": [
     "User"
    ],
    "summary": "Can Create Project?",
    "description": "Check whether your user has the ability to create more bare metal cloud projects.",
    "operationId": "canCreateProject",
    "security": [
     {
      "bearerAuth": [
       "projects"
      ]
     }
    ],
    "x-public": true,
    "x-version": "v2"
   }
  }
 },
 "components": {
  "securitySchemes": {
   "v1": {
    "type": "http",
    "description": "Basic auth for v1 endpoints",
    "scheme": "basic"
   },
   "bearerAuth": {
    "type": "http",
    "description": "Personal Access Token",
    "scheme": "bearer"
   }
  }
 }
}